### ISSUE TITLE
React example doesn't build

### ISSUE THREAD

**Issue by brownieboy** [unblu/visitor-js-api-example#25]
Trying to build the example in embedded-app-component/react.  The `npm run build` command threw an error concerning @unblu/embedded-app-component package being missing.  When I checked the node_modules folder, that package was actually symlinked to a local folder outside of the repo folder.

I worked around this by deleting the package-lock.json file then running `npm install` again.

I also had a TypeScript error in embedded-app-component/react/src/App.tsx:

```bash
No overload matches this call.
  The last overload gave the following error.
    Argument of type '(e: ViewModeChangeEvent) => void' is not assignable to parameter of type '(event: FullscreenChangeEvent) => void'.
      Types of parameters 'e' and 'event' are incompatible.
```

I used `@ts-ignore` to get out of that one for now:

```javascript
   componentWillUnmount() {
        // Make sure to remove the DOM listener when the component is unmounted.
        this.unbluElement?.removeEventListener("stateChange", this.onStateChange);
        // @ts-ignore
        this.unbluElement?.removeEventListener("viewModeChange", this.onViewModeChange);
    }
```

**Comment by davideberlein** [comment]
Thanks for the feedback @brownieboy. I'll fix the dependency issue asap.
I'll also have a look into the `removeEventListener` for `viewModeChange` looks like we're actually missing overloaded method there
